//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnionDatabaseV1.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class FileManager
    {
        public int Id { get; set; }
        public string Path { get; set; }
        public string Name { get; set; }
        public int Category { get; set; }
        public Nullable<int> PUK_ID { get; set; }
    
        public virtual PUK PUK { get; set; }
    }
}
