//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UnionDatabaseV1.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kepengurusan
    {
        public int Id { get; set; }
        public int PUK_ID { get; set; }
        public string Ketua { get; set; }
        public string Sekertaris { get; set; }
        public string Bendahara { get; set; }
        public string Waka1 { get; set; }
        public string Wasek1 { get; set; }
        public string Waka2 { get; set; }
        public string Wasek2 { get; set; }
        public string Waka3 { get; set; }
        public string Wasek3 { get; set; }
        public string Waka4 { get; set; }
        public string Wasek4 { get; set; }
        public string Waka5 { get; set; }
        public string Wasek5 { get; set; }
        public string Waka6 { get; set; }
        public string Wasek6 { get; set; }
    
        public virtual PUK PUK { get; set; }
    }
}
